openapi: "3.0.0"
info:
  version: 1.0.0
  title: Wallet Credential Issuer API
  description: This specification describes the six credential issuer endpoints required to issue credential(s) to the GOV.UK Wallet.
  license:
    name: MIT License
paths:
  /credential_offer:
    get:
      description: An endpoint for issuing a credential offer.
      responses:
        '200':
          description: |- 
            credential offer URL consisting of the following parts:<br>
            1. Wallet’s credential offer endpoint.<br>
            2. A query parameter `credential_offer`.<br>
            3. URL-encoded credential offer.
          content:
            application/json:
              schema:
                type: string
              example:
                https://mobile.build.account.gov.uk/wallet/add?credential_offer=%7B%22credentials%22%3A%5B%22FishingLicence%22%5D%2C%22grants%22%3A%7B%22urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Apre-authorized_code%22%3A%7B%22pre-authorized_code%22%3A%22eyJraWQiOiI1ZGNiZWU4NjNiNWQ3Y2MzMGM5YmExZjczOTNkYWNjNmMxNjYxMDc4MmU0YjZhMTkxZjk0YTdlOGIxZTE1MTBmIiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJhdWQiOiJodHRwczovL3Rva2VuLmJ1aWxkLmFjY291bnQuZ292LnVrIiwiY2xpZW50SWQiOiI8WU9VUiBPTkUgTE9HSU4gQ0xJRU5UIElEPiIsImlzcyI6Imh0dHBzOi8vZXhhbXBsZS1jcmVkZW50aWFsLWlzc3Vlci5tb2JpbGUuYnVpbGQuYWNjb3VudC5nb3YudWsiLCJjcmVkZW50aWFsX2lkZW50aWZpZXJzIjpbIjE2NTAwNWYwLTI4YjktNGFhMS05NTM4LTNmZThlZTc0N2Q0YiJdLCJleHAiOjE3Mzk0NTc3ODAsImlhdCI6MTczOTQ1NzQ4MH0.aZRv9KBCWRGLsi1Rd96jrzPxpQUkW68up0BYvUiF4RHjbLf6IxWn2PyU_ExOBAtEoj0lGAOOX7efOLMEc-lcIg%22%7D%7D%2C%22credential_issuer%22%3A%22https%3A%2F%2Fexample-credential-issuer.mobile.build.account.gov.uk%22%7D
  /credential:
    post:
      description: An endpoint used by the GOV.UK Wallet to request a Credential from the Credential Issuer.
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialRequestBody'
            example:
              proof:
                proof_type: jwt
                jwt: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDprZXk6ekRuYWVTR2ZTUU1Zdm5MYkxXRXViaGhHRFBvcTdwQTlNTU52dW12YnNtTUNab3ZVUiJ9.eyJpc3MiOiJ1cm46ZmRjOmdvdjp1azp3YWxsZXQiLCJhdWQiOiJodHRwczovL2V4YW1wbGUtY3JlZGVudGlhbC1pc3N1ZXIubW9iaWxlLmJ1aWxkLmFjY291bnQuZ292LnVrIiwiaWF0IjoxNzM5NDU3NTE3MzU1LCJub25jZSI6ImRiMmRiMzEzLTVjYjktNGJiNC1hYTRkLTlmZTRkYWM0MGJlMSJ9.7Ni5vVvTIf8jWGRsaxpjg7_o5rSGG_sttYKrC4184IUgtdjfsfqptClmO9_x62dyAgcbjeLqb1Q4YIIG8ZKNzA
      responses:
        '200':
          description: Credential.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CredentialResponse"
              example:
                credential: eyJraWQiOiI1ZGNiZWU4NjNiNWQ3Y2MzMGM5YmExZjczOTNkYWNjNmMxNjYxMDc4MmU0YjZhMTkxZjk0YTdlOGIxZTE1MTBmIiwiY3R5IjogInZjIiwidHlwIjogInZjK2p3dCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJodHRwczovL2V4YW1wbGUtY3JlZGVudGlhbC1pc3N1ZXIubW9iaWxlLmJ1aWxkLmFjY291bnQuZ292LnVrIiwic3ViIjoiZGlkOmtleTplYmZhZWIxZmQ3MTJlYmYxYzI3NmUxMmVjMjEiLCJpYXQiOiIxNzEyNjY0NzMxIiwibmJmIjoiMTcxMjY2NDczMSIsImV4cCI6IjE3NDQyMjE2NTciLCJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvbnMvY3JlZGVudGlhbHMvdjIiLCI8SlNPTi1MRCBDT05URVhUIFVSSSBGT1IgSVNTVUVSPiJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiRmlzaGluZ0xpY2VuY2UiXSwiaXNzdWVyIjoiaHR0cHM6Ly9leGFtcGxlLWNyZWRlbnRpYWwtaXNzdWVyLm1vYmlsZS5idWlsZC5hY2NvdW50Lmdvdi51ayIsIm5hbWUiOiJGaXNoaW5nIGxpY2VuY2UiLCJkZXNjcmlwdGlvbiI6IjxPUFRJT05BTCBDUkVERU5USUFMIERFU0NSSVBUSU9OPiIsInZhbGlkRnJvbSI6IjIwMjQtMDQtMDlUMTI6MTI6MTFaIiwidmFsaWRVbnRpbCI6IjIwMjgtMTItMTBUMjI6NTk6NTlaIiwiY3JlZGVudGlhbFN1YmplY3QiOnsiaWQiOiJkaWQ6a2V5OmViZmFlYjFmZDcxMmViZjFjMjc2ZTEyZWMyMSIsIm5hbWUiOlt7Im5hbWVQYXJ0cyI6W3sidmFsdWUiOiJTYXJhaCIsInR5cGUiOiJHaXZlbk5hbWUifSx7InZhbHVlIjoiRWR3YXJkcyIsInR5cGUiOiJGYW1pbHlOYW1lIn1dfV0sImZpc2hpbmdMaWNlbmNlIjpbeyJsaWNlbmNlTnVtYmVyIjoiMDA5ODc4ODYzIiwiaXNzdWFuY2VEYXRlIjogIjIwMjMtMTItMTAiLCJleHBpcmF0aW9uRGF0ZSI6ICIyMDI4LTEyLTEwIn1dfX0.FhJZpl4g6Vhi5G4hgLV_2ku_XlR9Eo8zX1Yj5hMOfLepwfI3YkD9xdNRUoMfKFwtB56bPQ6Fk6Q_2ePi5_N0aw
  /notification:
    post:
      description: An endpoint used by the GOV.UK Wallet to notify the Credential Issuer of events concerning Credential(s) it has issued.
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRequestBody'
            example:
              notification_id: 776aefd4-26c6-4a5f-aa7c-b5e294cd87cd
              event: credential_accepted
      responses:
        '204':
          description: No content.
  /.well-known/openid-credential-issuer:
    get:
      description: A public endpoint for the GOV.UK Wallet to retrieve metadata about the credential issuer.
      responses:
        '200':
          description: Credential issuer's metadata.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetadataResponse"
              example:
                credential_issuer: https://example-credential-issuer.mobile.build.account.gov.uk
                authorization_servers:
                    - https://token.build.account.gov.uk
                credential_endpoint: https://example-credential-issuer.mobile.build.account.gov.uk/credential
                notification_endpoint: https://example-credential-issuer.mobile.build.account.gov.uk/notification
                credential_configurations_supported:
                  fishingLicence:
                    format: jwt_vc_json
                    credential_definition:
                      type:
                        - VerifiableCredential
                        - FishingLicence
                    cryptographic_binding_methods_supported:
                      - did
                    cryptographic_suites_supported:
                      - ES256K
                    proof_types_supported:
                      jwt:
                        proof_signing_alg_values_supported:
                          - ES256
                        key_attestations_required:
                    display:
                      - name: Fishing Licence number
                        locale: en-GB
                        background_color: '#12107c'
                        text_color: '#FFFFFF'
                      - name: Rhif Trwydded Pysgota
                        locale: en-CY
                        background_color: '#12107c'
                        text_color: '#FFFFFF'
                    credentialSubject:
                      name:
                        - nameParts:
                            - display:
                                - name: Name
                                  locale: en-GB
                                - name: Enw
                                  locale: cy-GB
                      fishingLicenceRecord:
                        licenceNumber:
                          display:
                            - name: Fishing Licence number
                              locale: en-GB
                            - name: Rhif Trwydded Pysgota
                              locale: cy-GB
                        expirationDate:
                          display:
                            - name: Dyddiad dod i ben
                              locale: en-GB
                            - name: Rhif Trwydded Pysgota
                              locale: cy-GB
  /.well-known/did.json:
    get:
      description: A public endpoint for the GOV.UK Wallet to retrieve the Credential Issuer's public key represented as a DID Document.
      responses:
        '200':
          description: Credential Issuer's DID Document.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DidResponse"
              example:
                "@context":
                  - https://www.w3.org/ns/did/v1
                  - https://w3id.org/security/suites/jws-2020/v1
                id: did:web:example-credential-issuer.mobile.build.account.gov.uk
                verificationMethod:
                  - id: did:web:example-credential-issuer.mobile.build.account.gov.uk#5dcbee863b5d7cc30c9ba1f7393dacc6c16610782e4b6a191f94a7e8b1e1510f
                    type: JsonWebKey2020
                    controller: did:web:example-credential-issuer.mobile.build.account.gov.uk
                    publicKeyJwk:
                      kty: EC
                      kid: 5dcbee863b5d7cc30c9ba1f7393dacc6c16610782e4b6a191f94a7e8b1e1510f
                      crv: P-256
                      x: 6jCKX_QRrmTeEJi-uiwcYqu8BgMgl70g2pdAst24MPE
                      y: icPzjbSk6apD_SNvQt8NWOPlPeGG4KYU55GfnARryoY
                      alg: ES256
                assertionMethod:
                  - did:web:example-credential-issuer.mobile.build.account.gov.uk#5dcbee863b5d7cc30c9ba1f7393dacc6c16610782e4b6a191f94a7e8b1e1510f
  /.well-known/jwks.json:
    get:
      description: A public endpoint for GOV.UK One Login to retrieve the Credential Issuer's JSON Web Key Set (JWKS) of public keys.
      responses:
        '200':
          description: Credential Issuer's JWKS.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwksResponse"
              example:
                keys:
                  - kty: EC
                    use: sig
                    crv: P-256
                    kid: 5dcbee863b5d7cc30c9ba1f7393dacc6c16610782e4b6a191f94a7e8b1e1510f
                    x: 6jCKX_QRrmTeEJi-uiwcYqu8BgMgl70g2pdAst24MPE=
                    y: icPzjbSk6apD_SNvQt8NWOPlPeGG4KYU55GfnARryoY=
                    alg: ES256
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CredentialRequestBody:
      type: object
      properties:
        proof:
          $ref: "#/components/schemas/Proof"
      required:
        - proof
    Proof:
      type: object
      additionalProperties: false
      properties:
        proof_type:
          type: string
          enum: [ jwt ]
        jwt:
          type: string
          format: jwt
      required:
        - jwt
        - proof_type
    CredentialResponse:
      type: object
      properties:
        credential:
          description: Credential signed as a JWT.
          type: string
          format: jwt
      required:
        - credential
    NotificationRequestBody:
      type: object
      properties:
        notification_id:
          type: string
          format: uuid
        event:
          type: string
          enum:
            - credential_accepted
            - credential_failure
            - credential_deleted
        event_description:
          type: string
      required:
        - notification_id
        - event
    MetadataResponse:
      type: object
      properties:
        credential_issuer:
          description: URL of the credential issuer.
          type: string
          format: uri
        credential_endpoint:
          description: URL of the credential issuer's credential endpoint.
          type: string
          format: uri
        notification:
          description: URL of the credential issuer's notification endpoint.
          type: string
          format: uri
        authorization_servers:
          description: Set containing the URL of the authorization server(s) the credential issuer relies on for authorization.
          type: array
          items:
            type: string
            format: uri
        credential_configurations_supported:
          $ref: '#/components/schemas/CredentialConfigurationsSupported'
      required:
        - authorization_servers
        - credential_configurations_supported
        - credential_endpoint
        - credential_issuer
    CredentialConfigurationsSupported:
      description: Information about the credential(s) issued by the credential issuer.
      type: object
      properties:
        fishingLicence:
          $ref: '#/components/schemas/FishingLicence'
      required:
        - fishingLicence
    FishingLicence:
      description: A credential issued by the credential issuer.
      type: object
      properties:
        format:
          description: Format of the credential.
          type: string
        credential_definition:
          $ref: '#/components/schemas/CredentialDefinition'
        cryptographic_binding_methods_supported:
          description: Set of methods available for cryptographically binding the issued credential.
          type: array
          items:
            type: string
        credential_signing_alg_values_supported:
          description: Set of algorithms that the credential issuer uses to sign the credential.
          type: array
          items:
            type: string
        proof_types_supported:
          $ref: '#/components/schemas/ProofTypesSupported'
        display:
          description: Display properties of the credential, such as the display name, logo, background colour, etc.
          type: array
          items:
            $ref: '#/components/schemas/FishingLicenceDisplay'
        credentialSubject:
          $ref: '#/components/schemas/CredentialSubject'
      required:
        - credentialSubject
        - credential_definition
        - credential_signing_alg_values_supported
        - cryptographic_binding_methods_supported
        - display
        - format
        - proof_types_supported
    CredentialDefinition:
      description: Description of the credential type.
      type: object
      properties:
        type:
          type: array
          items:
            type: string
      required:
        - type
    ProofTypesSupported:
      description: Key proof(s) supported by the credential issuer.
      type: object
      properties:
        jwt:
          $ref: '#/components/schemas/Jwt'
      required:
        - jwt
    Jwt:
      type: object
      properties:
        proof_signing_alg_values_supported:
          type: array
          items:
            type: string
        key_attestations_required:
          type: object
      required:
        - key_attestations_required
        - proof_signing_alg_values_supported
    KeyAttestationsRequired:
      type: object
    FishingLicenceDisplay:
      type: object
      properties:
        name:
          type: string
        locale:
          type: string
        background_color:
          type: string
        text_color:
          type: string
      required:
        - background_color
        - locale
        - name
        - text_color
    CredentialSubject:
      description: Display properties of the subject of the credential.
      type: object
      properties:
        name:
          type: array
          items:
            $ref: '#/components/schemas/Name'
        fishingLicenceRecord:
          $ref: '#/components/schemas/FishingLicenceRecord'
      required:
        - fishingLicenceRecord
        - name
    Name:
      type: object
      properties:
        nameParts:
          type: array
          items:
            $ref: '#/components/schemas/NameParts'
      required:
        - nameParts
    NameParts:
      type: object
      properties:
        display:
          type: array
          items:
            $ref: '#/components/schemas/Display'
      required:
        - display
    Display:
      type: object
      properties:
        name:
          type: string
        locale:
          type: string
      required:
        - locale
        - name
    FishingLicenceRecord:
      type: object
      properties:
        licenceNumber:
          $ref: '#/components/schemas/LicenceNumber'
        expirationDate:
          $ref: '#/components/schemas/ExpirationDate'
      required:
        - licenceNumber
        - expirationDate
    LicenceNumber:
      type: object
      properties:
        display:
          type: array
          items:
            $ref: '#/components/schemas/Display'
      required:
        - display
    ExpirationDate:
      type: object
      properties:
        display:
          type: array
          items:
            $ref: '#/components/schemas/Display'
      required:
        - display
    DidResponse:
      type: object
      properties:
        '@context':
          description: Set of URL contexts which define the terms used in the DID Document.
          type: array
          minItems: 1
          items:
            type: string
            format: uri
        id:
          description: Unique identifier of the DID Document itself.
          type: string
        verificationMethod:
          description: Set of verification methods, such as cryptographic public keys.
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/VerificationMethod"
        assertionMethod:
          description: Set of DID URLs where each URL uniquely identifies a specific key within the DID Document.
          type: array
          minItems: 1
          items:
            type: string
      required:
        - '@context'
        - assertionMethod
        - id
        - verificationMethod
    VerificationMethod:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        controller:
          type: string
        publicKeyJwk:
          $ref: "#/components/schemas/PublicKeyJwk"
      required:
        - id
        - type
        - controller
        - publicKeyJwk
    PublicKeyJwk:
      type: object
      properties:
        kty:
          description: Key Type. The family of cryptographic algorithms used with the key.
          type: string
          enum:
            - EC
        kid:
          description: Key ID. Unique identifier sed to match a specific key.
          type: string
        crv:
          description: Curve. Cryptographic curve used with the key.
          type: string
          enum:
            - P-256
        x:
          description: The "x" coordinate for the elliptic curve point.
          type: string
        y:
          description: The "y" coordinate for the elliptic curve point.
          type: string
        alg:
          description: Algorithm. The cryptographic algorithm used with the key.
          type: string
          enum:
            - P-256
      required:
        - kty
        - kid
        - crv
        - x
        - y
        - alg
    JwksResponse:
      type: object
      properties:
        keys:
          description: Set of public keys in JWK format.
          type: array
          items:
            $ref: '#/components/schemas/Key'
      required:
        - keys
    Key:
      allOf:
        - $ref: "#/components/schemas/PublicKeyJwk"
        - type: object
          properties:
            use:
              description: The intended use of the key.
              type: string
              enum:
                - sig
          required:
            - use