openapi: "3.0.0"
info:
  version: 1.0.0
  title: Example CRI
  license:
    name: MIT
paths:
  /credential_offer:
    get:
      summary: Request a credential offer
      description: Private API for the CRI to request a credential offer
      parameters:
        - name: documentId
          in: path
          description: ID of the document for which the offer must be issued
          required: true
          schema:
            type: string
            format: uuid
        - name: walletSubjectId
          in: path
          description: Pairwise identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: URI encoded credential offer
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/CredentialOffer"
  /credential:
    post:
      summary: Request a credential
      description: API for the wallet to request the credential
      security:
        - BearerAuhentication: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialRequestBody'
      responses:
        '200':
          description: Credential
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Credential"
  /.well-known/openid-credential-issuer:
    get:
      summary: Retrieve credential metadata
      description: Public API for other systems to retrieve metadata about the credentials issued by this CRI
      responses:
        '200':
          description: Credential metadata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CredentialMetadata"
  /.well-known/did.json:
    get:
      summary: Retrieve did:web document
      description: Public API for other systems to retrieve the did:web document for this CRI
      responses:
        '200':
          description: did:web document
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DidWebDocument"
components:
  securitySchemes:
    BearerAuthentication:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CredentialOffer:
      type: object
      required:
        - credential_offer_uri
      properties:
        credential_offer_uri:
          type: string
          format: uri
          example: "https://mobile.staging.account.gov.uk/wallet/add?credential_offer=%7B%22credential_issuer%22:%22
  https://credential-issuer.example.com%22,%22credentials%22:%5B%22UniversityDegree_JWT
  %22,%7B%22format%22:%22mso_mdoc%22,%22doctype%22:%22org.iso.18013.5.1.mDL%22%7D%5D,%22
  grants%22:%7B%22authorization_code%22:%7B%22issuer_state%22:%22eyJhbGciOiJSU0Et...FYUaBy
  %22%7D,%22urn:ietf:params:oauth:grant-type:pre-authorized_code%22:%7B%22
  pre-authorized_code%22:%22adhjhdjajkdkhjhdj%22,%22user_pin_required%22:true%7D%7D%7D"
    CredentialRequestBody:
      type: object
      additionalProperties: false
      properties:
        credential_identifier:
          type: string
        proof:
          $ref: "#/components/schemas/Proof"
      required:
        - credential_identifier
        - proof
    Proof:
      type: object
      additionalProperties: false
      properties:
        proof_type:
          type: string
          enum: [ jwt ]
        jwt:
          type: string
          format: jwt
      required:
        - jwt
        - proof_type
    Credential:
      type: object
      additionalProperties: false
      properties:
        iss:
          type: string
          format: uri
        sub:
          type: string
        vc:
          $ref: "#/components/schemas/Vc"
      required:
        - iss
        - sub
        - vc
    Vc:
      type: object
      additionalProperties: false
      properties:
        "@context":
          type: array
          items:
            type: string
            format: uri
        type:
          type: array
          items:
            type: string
        credentialSubject:
          $ref: "#/components/schemas/CredentialSubject"
      required:
        - "@context"
        - credentialSubject
        - type
    CredentialSubject:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        issuanceDate:
          type: string
          format: date
        expirationDate:
          type: string
          format: date
        name:
          type: array
          items:
            $ref: "#/components/schemas/Name"
        birthDate:
          type: array
          items:
            $ref: "#/components/schemas/BirthDate"
        address:
          type: array
          items:
            $ref: "#/components/schemas/Address"
        BasicDisclosureRecord:
          type: array
          items:
            $ref: "#/components/schemas/BasicDisclosureRecord"
        documentMetadata:
          type: array
          items:
            $ref: "#/components/schemas/DocumentMetadatum"
      required:
        - BasicDisclosureRecord
        - address
        - birthDate
        - documentMetadata
        - expirationDate
        - id
        - issuanceDate
        - name
    BasicDisclosureRecord:
      type: object
      additionalProperties: false
      properties:
        certificateNumber:
          type: string
        outcome:
          type: string
        disclosureDate:
          type: string
          format: date
      required:
        - certificateNumber
        - disclosureDate
        - outcome
    Address:
      type: object
      additionalProperties: false
      properties:
        firstLine:
          type: string
      required:
        - firstLine
    BirthDate:
      type: object
      additionalProperties: false
      properties:
        value:
          type: string
          format: date
      required:
        - value
    DocumentMetadatum:
      type: object
      additionalProperties: false
      properties:
        multipleCredentialsAllowed:
          type: string
          format: boolean
      required:
        - multipleCredentialsAllowed
    Name:
      type: object
      additionalProperties: false
      properties:
        nameParts:
          type: array
          items:
            $ref: "#/components/schemas/NamePart"
      required:
        - nameParts
    NamePart:
      type: object
      additionalProperties: false
      properties:
        value:
          type: string
        type:
          type: string
      required:
        - type
        - value
    CredentialMetadata:
      type: object
      additionalProperties: false
      properties:
        credential_issuer:
          type: string
          format: uri
        authorization_server:
          type: string
          format: uri
        credentials_endpoint:
          type: string
          format: uri
        credentials_supported:
          $ref: "#/components/schemas/CredentialsSupported"
      required:
        - authorization_server
        - credential_issuer
        - credentials_endpoint
        - credentials_supported
    CredentialsSupported:
      type: object
      additionalProperties: false
      properties:
        basicDisclosure:
          $ref: "#/components/schemas/BasicDisclosure"
      required:
        - basicDisclosure
    BasicDisclosure:
      type: object
      additionalProperties: false
      properties:
        format:
          type: string
        id:
          type: string
        types:
          type: array
          items:
            type: string
        cryptographic_binding_methods_supported:
          type: array
          items:
            type: string
        cryptographic_suites_supported:
          type: array
          items:
            type: string
        display:
          type: array
          items:
            $ref: "#/components/schemas/BasicDisclosureDisplay"
        credentialSubject:
          $ref: "#/components/schemas/CredentialSubjectMetadata"
      required:
        - credentialSubject
        - cryptographic_binding_methods_supported
        - cryptographic_suites_supported
        - display
        - format
        - id
        - types
    CredentialSubjectMetadata:
      type: object
      additionalProperties: false
      properties:
        lastName:
          $ref: "#/components/schemas/CertificateNumber"
        givenName:
          $ref: "#/components/schemas/CertificateNumber"
        dateOfBirth:
          $ref: "#/components/schemas/CertificateNumber"
        firstLineOfAddress:
          $ref: "#/components/schemas/CertificateNumber"
        BasicdisclosureRecord:
          $ref: "#/components/schemas/BasicdisclosureRecord"
        outcome:
          $ref: "#/components/schemas/CertificateNumber"
        disclosureDate:
          $ref: "#/components/schemas/CertificateNumber"
        certificateNumber:
          $ref: "#/components/schemas/CertificateNumber"
      required:
        - BasicdisclosureRecord
        - certificateNumber
        - dateOfBirth
        - disclosureDate
        - firstLineOfAddress
        - givenName
        - lastName
        - outcome
    BasicdisclosureRecord:
      type: object
      additionalProperties: false
    CertificateNumber:
      type: object
      additionalProperties: false
      properties:
        display:
          type: array
          items:
            $ref: "#/components/schemas/CertificateNumberDisplay"
      required:
        - display
    CertificateNumberDisplay:
      type: object
      additionalProperties: false
      properties:
        field:
          type: string
        name:
          type: string
        locale:
          $ref: "#/components/schemas/Locale"
      required:
        - field
        - locale
        - name
    BasicDisclosureDisplay:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        locale:
          type: string
        logo:
          $ref: "#/components/schemas/Logo"
        background_color:
          type: string
        text_color:
          type: string
      required:
        - background_color
        - locale
        - logo
        - name
        - text_color
    Logo:
      type: object
      additionalProperties: false
      properties:
        url:
          type: string
          format: uri
        alt_text:
          type: string
      required:
        - alt_text
        - url
    Locale:
      type: string
      enum:
        - en-GB
        - cy-GB
    DidWebDocument:
      type: object
      additionalProperties: false
      properties:
        context:
          type: array
          items:
            type: string
            format: uri
        id:
          type: string
        verificationMethod:
          type: array
          items:
            $ref: "#/components/schemas/VerificationMethod"
        assertionMethod:
          type: array
          items:
            type: string
      required:
        - assertionMethod
        - context
        - id
        - verificationMethod
    VerificationMethod:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        type:
          type: string
        controller:
          type: string
        publicKeyJwk:
          $ref: "#/components/schemas/PublicKeyJwk"
      required:
        - controller
        - id
        - publicKeyJwk
        - type
    PublicKeyJwk:
      type: object
      additionalProperties: false
      properties:
        kid:
          type: string
        kty:
          type: string
        crv:
          type: string
        x:
          type: string
        y:
          type: string
      required:
        - crv
        - kid
        - kty
        - x
        - y
