sequenceDiagram
    autonumber
    actor User as User
    participant CRI as Credential Issuer
    participant App as App
    participant OneLogin as OneLogin
    activate User
    User->>CRI: Access
    activate CRI
    CRI->>OneLogin: Authenticates user: GET /authorize
    activate OneLogin
    OneLogin-->>CRI: Redirects user to your `redirect_uri` with `authorization_code`
    deactivate OneLogin
    CRI->>OneLogin: Exchanges `authorization_code` for tokens: POST /token
    activate OneLogin
    OneLogin-->>CRI: Returns token response (`access_token` & `id_token`)
    deactivate OneLogin
    CRI->>OneLogin: Exchanges `access_token` for user information: POST /userinfo
    activate OneLogin
    OneLogin-->>CRI: Returns user information
    deactivate OneLogin
    CRI->>CRI: Extracts wallet_subject_id from user information
    CRI->>CRI: Generates `credential_identifier` (UUID)
    CRI->>CRI: Stores `wallet_subject_id` against `credential_identifier`
    CRI->>CRI: Builds Pre-Authorized Code (JWT)
    CRI->>CRI: Signs Pre-Authorized Code with CRI's private key
    CRI->>CRI: Builds Credential Offer object
    CRI-->>User: Present Credential Offer as QR code
    deactivate CRI
    User->>App: Opens app
    activate App
    App-->OneLogin: Authenticates user
    activate OneLogin
    OneLogin-->>App: User is authenticated
    deactivate OneLogin
    User->>App: Scans QR code
    App->>App: Validates Credential Offer
    App->>App: Extracts CRI's URL from Credential Offer
    App->>CRI: Fetches CRI's Metadata: GET /.well-known/openid-credential-issuer
    activate CRI
    CRI-->>App: Returns CRI's Metadata
    deactivate CRI
    App->>App: Extracts Authorization Server's URL from Metadata
    App->>OneLogin: Exchanges Pre-Authorized Code for access token
    activate OneLogin
    OneLogin->>OneLogin: Uses `clientId` in  Pre-Authorized Code<br> to find CRI's JWKS URL
    OneLogin->>CRI: Fetches CRI's public keys: `GET /.well-known/jwks.json`
    activate CRI
    CRI-->>OneLogin: Returns its JSON Web Key Set
    deactivate CRI
    OneLogin->>OneLogin: Verifies Pre-Authorized Code signature
    OneLogin-->>App: Issues access token
    deactivate OneLogin
    App->>App: Builds Proof (JWT) and signs it with app's private key
    note over App: JWT header includes public key in did:key format
    App->>CRI: Fetches Credential: `POST /credential`
    activate CRI
    opt if public key not in cache or invalid
        CRI->>OneLogin: Fetches One Login's public keys: `GET /.well-known/jwks.json`
        activate OneLogin
        OneLogin-->>CRI: Returns its JSON Web Key Set
        deactivate OneLogin
    end
    CRI->>CRI: Verifies access token signature
    CRI->>CRI: Extracts credential_identifiers claim and looks up crdential
    CRI->>CRI: ADD ALL VEIRIFICATION STEPS
    CRI->>CRI: Validate sub claim on access token == walletAccountId
    CRI->>CRI: Validate proof of did:key ownership using `jwt` proof type
    CRI->>CRI: Build credential and bind to wallet did:key
    CRI-->>App: Credential
    deactivate CRI
    App->>CRI: Fetches CRI's public key: `GET /.well-known/did.json`
    activate CRI
    CRI-->>App: Returns its public key as a DID document
    deactivate CRI
    App->>App: Verifies signature and content of credential
    App->>App: Securely stores credential
    activate CRI
    App-->>CRI: Notifies of success or failure: `POST /notification`
    CRI-->>CRI: Records notification of success or failure
    CRI-->>App: Returns 204 No Content
    deactivate CRI
    deactivate App
    deactivate User